[connections.postgresql]
dialect = "postgresql"
host = "36.67.62.245"
port = 8088
database = "dbpresales"
username = "admin"
password = "bzftDFqgCxGg0gQ"

[smtp]
server = "smtp.gmail.com"
port = 587
email = "krisawahyukurniawan@gmail.com"
password = "lijx qhtr nnqh pcus"